# .github/workflows/trigger-codemagic-concurrent.yml

name: Trigger Concurrent Codemagic Builds

on:
  # schedule:
  #   - cron: '0 0-23/2 * * *' # Commented out for manual testing

  workflow_dispatch:

jobs:
  trigger_builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (optional, if you need files from repo)
        uses: actions/checkout@v4

      - name: Send Webhook Trigger 1 to Codemagic (Simplified Payload)
        id: trigger_1
        run: |
          echo "Triggering Codemagic build 1 for workflow: my-npm-workflow (simplified payload)"
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "workflowId": "my-npm-workflow" # <<< IMPORTANT: REPLACE WITH YOUR ACTUAL CODEMAGIC WORKFLOW ID
            }' \
            "${{ secrets.CODEMAGIC_WEBHOOK_URL }}"
        env:
          CODEMAGIC_WEBHOOK_URL: ${{ secrets.CODEMAGIC_WEBHOOK_URL }}

      - name: Send Webhook Trigger 2 to Codemagic (Simplified Payload)
        id: trigger_2
        run: |
          echo "Waiting 5 seconds before triggering build 2..."
          sleep 5
          echo "Triggering Codemagic build 2 for workflow: my-npm-workflow (simplified payload)"
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "workflowId": "my-npm-workflow" # <<< IMPORTANT: REPLACE WITH YOUR ACTUAL CODEMAGIC WORKFLOW ID
            }' \
            "${{ secrets.CODEMAGIC_WEBHOOK_URL }}"
        env:
          CODEMAGIC_WEBHOOK_URL: ${{ secrets.CODEMAGIC_WEBHOOK_URL }}

      - name: Send Webhook Trigger 3 to Codemagic (Simplified Payload)
        id: trigger_3
        run: |
          echo "Waiting 5 seconds before triggering build 3..."
          sleep 5
          echo "Triggering Codemagic build 3 for workflow: my-npm-workflow (simplified payload)"
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{
              "workflowId": "my-npm-workflow" # <<< IMPORTANT: REPLACE WITH YOUR ACTUAL CODEMAGIC WORKFLOW ID
            }' \
            "${{ secrets.CODEMAGIC_WEBHOOK_URL }}"
        env:
          CODEMAGIC_WEBHOOK_URL: ${{ secrets.CODEMAGIC_WEBHOOK_URL }}

      - name: Log all triggers sent
        run: |
          echo "All Codemagic build triggers sent for this manual run."
