name: Trigger Concurrent Codemagic Builds

on:
  # schedule:
  #   - cron: '0 0-23/2 * * *' # Commented out for manual testing

  workflow_dispatch:

jobs:
  trigger_builds:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (optional, if you need files from repo)
        uses: actions/checkout@v4

      - name: Send Webhook Trigger 1 to Codemagic (via REST API)
        id: trigger_1
        run: |
          echo "Triggering Codemagic build 1 for workflow: default-workflow (via REST API)"
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-auth-token: ${{ secrets.CODEMAGIC_API_TOKEN }}" \
            -d '{
              "appId": "687d20ef26b4bb16b4fb07bf",
              "workflowId": "default-workflow",
              "branch": "main",
              "message": "Triggered by GA Manual Test - Build 1"
            }' \
            "https://api.codemagic.io/builds"
        env:
          CODEMAGIC_API_TOKEN: ${{ secrets.CODEMAGIC_API_TOKEN }}

      - name: Send Webhook Trigger 2 to Codemagic (via REST API)
        id: trigger_2
        run: |
          echo "Waiting 5 seconds before triggering build 2..."
          sleep 5
          echo "Triggering Codemagic build 2 for workflow: default-workflow (via REST API)"
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-auth-token: ${{ secrets.CODEMAGIC_API_TOKEN }}" \
            -d '{
              "appId": "687d20ef26b4bb16b4fb07bf",
              "workflowId": "default-workflow",
              "branch": "main",
              "message": "Triggered by GA Manual Test - Build 2"
            }' \
            "https://api.codemagic.io/builds"
        env:
          CODEMAGIC_API_TOKEN: ${{ secrets.CODEMAGIC_API_TOKEN }}

      - name: Send Webhook Trigger 3 to Codemagic (via REST API)
        id: trigger_3
        run: |
          echo "Waiting 5 seconds before triggering build 3..."
          sleep 5
          echo "Triggering Codemagic build 3 for workflow: default-workflow (via REST API)"
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "x-auth-token: ${{ secrets.CODEMAGIC_API_TOKEN }}" \
            -d '{
              "appId": "687d20ef26b4bb16b4fb07bf",
              "workflowId": "default-workflow",
              "branch": "main",
              "message": "Triggered by GA Manual Test - Build 3"
            }' \
            "https://api.codemagic.io/builds"
        env:
          CODEMAGIC_API_TOKEN: ${{ secrets.CODEMAGIC_API_TOKEN }}

      - name: Log all triggers sent
        run: |
          echo "All Codemagic build triggers sent for this manual run."
